### ISSUE TITLE
Email us when it looks like a benchmark crashed

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/tfb-status#4]
Our continuous benchmarks will sometimes crash, requiring manual intervention.  When this happens, it tends to go unnoticed for days.

Change tfb-status to send an email when it looks like a run has crashed.

How do we tell when a run has crashed?  How about:
* The most recent run in a given environment has not completed.
* It's been over X hours since we last got an update for that run.

**Comment by msmith-techempower** [comment]
After reviewing [a log](https://tfb-status.techempower.com/unzip/results.2018-07-24-09-23-41-359.zip/results/20180721172028/benchmark.log) for a bit, it looks like no test implementation takes more than ~20 minutes to complete.

A conservative, and quick-notifying, approach would be:
* Most recent run has not completed
* It has been 30 minutes since last update

**Comment by michaelhixson** [comment]
This was implemented a while ago.
